apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # https://www.rabbitmq.com/kubernetes/operator/install-operator
  # https://github.com/rabbitmq/cluster-operator/releases
  - https://github.com/rabbitmq/cluster-operator/releases/download/v2.19.0/cluster-operator.yml
