apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:

  # The RabbitMQ Cluster Kubernetes Operator automates provisioning, management, and operations of RabbitMQ clusters running on Kubernetes.
  # The RabbitMQ Messaging Topology Operator manages RabbitMQ messaging topologies within a RabbitMQ cluster deployed via the RabbitMQ Cluster Kubernetes Operator.
  # https://www.rabbitmq.com/kubernetes/operator/operator-overview

  # rabbitmq-cluster-operator
  # https://www.rabbitmq.com/kubernetes/operator/install-operator
  # https://github.com/rabbitmq/cluster-operator/releases
  - https://github.com/rabbitmq/cluster-operator/releases/download/v2.19.0/cluster-operator.yml

  # messaging-topology-operator
  # https://www.rabbitmq.com/kubernetes/operator/install-topology-operator
  # https://github.com/rabbitmq/messaging-topology-operator/releases
  - https://github.com/rabbitmq/messaging-topology-operator/releases/download/v1.18.2/messaging-topology-operator-with-certmanager.yaml
