---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
  - pairs:
resources:
  - gotk-components.yaml
  - gotk-sync.yaml
  - cert-manager-custom-resources.yaml
  - cert-manager.yaml

  # Removing this until I can find a sufficiently self-sovereign, free DNS provider.
  # - external-dns.yaml

  - imagepolicies.yaml
  - imagerepositories.yaml
  - imageupdateautomation.yaml
  - ingress-nginx.yaml
  - sops-age.secrets.yaml
  - kubernetes-dashboard.yaml
  - metallb.yaml
  - metallb-custom-resources.yaml
