sops:
    age:
        - recipient: age1hyw8w5vnp0kxrrcdd02f30r3euyszyaxs04qnw8d0jnmf9vuhyuq6qz9k8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQRG5NWTdONUFjVm9Ecnds
            Tm0wNFUrdDlSOCs3M3hGMStYOGgvaTNUNGk4Ckw4NWFHNklJMGFFRVVKUU1UZjZr
            N05jVm9kcEpqSGxWckVodlJGZUcwS2cKLS0tIEdjbkliU2lNajJ0bFhrdFE4OFJo
            QThVVFpwTnBJS1ZyZ2RUNE8rK0xubjAKpeu44hjknt/Rr6WNpnp5Knm0HURg2onu
            0WcNzpNTuQXM+SIhnSIiCOFeJi39ramfsJx1d27lkxBgGVxQ/SKJTQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-26T23:34:59Z"
    mac: ENC[AES256_GCM,data:5JkGmjt4KstBf4y/qruyIz9PKVpFwkSAroniFv76wjJxAfhG9dPmC7A5UAA7lKRARU4N9vPUGoJuci3Ff+oYH3ppHVpZ3+ilxiCcjhG09Hxb9CZMPZsrtnzrfgsM3rRXXKo4mvhwpVqc7M/l9rtLsdRRHIPDSzlHQtWUUxCP0Ro=,iv:O+XVOhCyXunJTnTcpxKB16xyHutuFB/KlWUm1UCkFTk=,tag:lAnZ5Os790HwVQYgQCERnw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
