sops:
    age:
        - recipient: age1gscn4gwwg0z054vx4lknzav7vm3060h2dq3rualh0fcm6ng59d4sqvtwp5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3SHAwY25UOEtia2Z6cG5z
            Z3h1WXlJbk1tQ1hEZ1RwKy9qdTI4elZIdG1vCkJuVHlKeFY2MGE5RjVoZHdzei9q
            cmR1bE1PeHo5aXpMR0RHSnNySGZIbDQKLS0tIEpsTE1Ic3FJaUNHUmQwWVkzMy9q
            dTNJVXFxSlNNZHZSbGlSSDUvTStnQ0UKVA7htxewlbXRXJmvbKvTq7yDnXLZRydf
            D57Y31p3Fqg2lSBsk8VB21lqJZ2fZcC0WAF6hf2dS1wg5Gp/SWj3wQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-18T15:20:39Z"
    mac: ENC[AES256_GCM,data:5eVrmeX3LKDhOQB9DKeSQHhd+1bY6IPSlBt53eNfoeHwRU0IGLLDHOXH83VPFReLsov6EucqBa2TDVWu7Q96t88Ji6ElR4YZEepsJkxjMEs6u2xYvbYvSijC71eqWaI7j1zSa2M67vVfR0BUdL/5h8zt/LwkjcX+2K59UejLydc=,iv:tjUJ8i7uUklv9quTjxJUsL6xL1FXJXFdTlkiAI2vIpA=,tag:vqQuOMqnznj0UdpjZ/OIuQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
