# https://fluxcd.io/flux/components/helm/helmreleases/
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: app-template
spec:

  # HelmRepository example
  # chart:
  #   spec:
  #     chart: app-template
  #     version: 0.0.0
  #     sourceRef:
  #       kind: HelmRepository
  #       name: prometheus-community

  # OCIRepository example
  # chartRef:
  #   kind: OCIRepository
  #   name: devopscoop-app
  #   # TODO: Is namespace needed?
  #   # namespace: app-template

  interval: 10m
  valuesFrom:
    - kind: ConfigMap
      name: app-template-values
    - kind: Secret
      name: app-template-secrets
